<?php

/**
 * Class ExamplePlugin.
 */
class ExamplePlugin {

  /**
   * ExamplePlugin constructor.
   *
   * @param $plugin
   */
//  public function __construct($plugin) {
//    $plugin = [
//      'title' => t('Example content type plugin'), // Название плагина, отображаемое при его выборе.
//      'description' => t('The output a custom text.'), // Описание плагина, отображаемое при его выборе.
//      'render callback' => 'example_text_content_type_render', // Функция, которая будет формировать и выводить содержимое плагина.
//      'edit form' => 'example_text_edit_form', // Форма с настройками плагина.
//      'category' => t('Custom panes'), // Категория, в которой будет находиться плагин.
//      'single' => TRUE, // Флаг, указывающий является ли плагин подтипом другого.
//    ];
//  }

}
