<?php

/**
 * @file
 * Contains mt_service.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mt_service_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mt_service module.
    case 'help.page.mt_service':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configure the content and layout of the Service Content Type.') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function mt_service_theme() {
  // Theme for mt_service module.
  $themes['mt_service'] = [
    'template'  => 'mt_service',
    'variables' => [
      'data' => NULL,
    ],
  ];

  return $themes;

}
