<?php

/**
 * @file
 * Contains mt_team_member.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mt_team_member_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mt_team_member module.
    case 'help.page.mt_team_member':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configure the content and layout of the Team Member Content Type.') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function mt_team_member_theme() {
  // Theme for mt_team_member module.
  $themes['mt_team_member'] = [
    'template'  => 'mt_team_member',
    'variables' => [
      'data' => NULL,
    ],
  ];

  return $themes;

}
