<?php

/**
 * @file
 * Contains test_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_module module.
    case 'help.page.test_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test Module for different features.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function test_module_preprocess_html(&$variables) {
//  $random_message = \Drupal::service('test_module.random_message')->getRandomMessage();
//  drupal_set_message($random_message);
  \Drupal::service('test_module.random_drupal_message')->setRandomMessage();
}
